apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana-llm
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc:8428
        isDefault: true
        editable: true
